require("GamePlay/Interflow/DataToCSharpMgr")
require("GamePlay/Resource/ResourceConfig")
require("GamePlay/PoolManager/PoolManagerTest")
require("GamePlay/Preload/PreloadManager")
require("GamePlay/Reconnect/ReconnectManager")
require("GamePlay/MainCamera")
require("GamePlay/Effect/Effect")
require("GamePlay/Pickup/PickupManager")
require("GamePlay/Scene/Scene")
require("GamePlay/Role/RoleManager")
require("GamePlay/ActivityManager/ActivityManager")
require("GamePlay/BlockBuilding/BlockBuildManager")
require("GamePlay/Traps/TrapManager")
require("GamePlay/BehaviorTree/BTManager")
require("GamePlay/DropItem/DropItemManager")
require("GamePlay/Equip/EquipEffectSet")
require("GamePlay/TouchEvent")
require("GamePlay/FightFramework/SkillMgr")
require("GamePlay/FightFramework/SkillEnum")
require("GamePlay/Guide/GuideManager")
require("GamePlay/FightFramework/RoleTarget/RoleTargetManager")
require("GamePlay/FightFramework/RoleTarget/AutoFightFindTargetManager")
require("GamePlay/Scene/SceneTouchEffect")
require("GamePlay/Scene/SceneTerrainEffect")
require("GamePlay/Scene/MonsterTouchEffect")
require("GamePlay/Scene/SceneWeatherEffect")
require("GamePlay/Scene/SceneGrassEffectManager")
require("GamePlay/PointMgr")
require("GamePlay/ItemBox/ItemBoxDisplayManager")
require("GamePlay/Condition/ConditionManager")
require("GamePlay/MapEffect/MapEffectManager")
require("GamePlay/Vip/VipManager")
require("GamePlay/RedNameManager/RedNameManager")
require("GamePlay/FSMSystem/FSMSystem")
require("GamePlay/Cost/Cost_ItemCombine")
require("GamePlay/Trans/TransManager")
require("GamePlay/Grave/GraveManager")
require("GamePlay/ItemCell/DragItemManager")
require("GamePlay/Resource/InstantiateManager")
require("GamePlay/Task/LeftTopPanelManager")
require("GamePlay/itemTextPrompt/TextPrompt")
require("GamePlay/Task/AutoTaskManager")
require("GamePlay/Task/TaskManager")
require("GamePlay/MapMonster/MapMonsterLockManager")
require("GamePlay/Task/FightMonsterManager")
require("GamePlay/Path/PathFinderManager")
require("GamePlay/Logs/ErrorLog/LogManager")
require("GamePlay/Logs/ActionLog/ActionStepsLogManager")
require("GamePlay/Logs/Role/RoleDeclareManager")
require("GamePlay/Logs/ActionLog/CommercializeLogManager")
require("GamePlay/HotUpdate/HotUpdateMgr")
require("GamePlay/Logs/Risk/RiskSpotManager")
GamePlay = {}
local this = GamePlay

function GamePlay.Init()
  EventManager.Regist(Event.GamePlay_Enter, this.OnEnterGame)
  EventManager.Regist(Event.GamePlay_Leave, this.OnLeaveGame)
  EventManager.Regist(Event.GamePlay_Back2Choose, this.OnBack2Choose)
end

function GamePlay.OnEnterGame()
  this.playing = true
  RoleManager.OnEnterGame()
  ActivityManager.OnEnterGame()
  RedNameManager.OnEnterGame()
  BlockBuildManager.OnEnterGame()
  TrapManager.OnEnterGame()
  DropItemManager.OnEnterGame()
  SceneController.OnEnterGame()
  TouchEvent.OnEnterGame()
  PickupManager.OnEnterGame()
  MapEffectManager.OnEnterGame()
  DynamicTerrainController.OnEnterGame()
  TransManager.OnEnterGame()
  GraveManager.OnEnterGame()
  SceneGrassEffectManager.OnEnterGame()
  GuideManager.OnEnterGame()
  VipManager.OnEnterGame()
  SceneClientUpdateView.OnEnterGame()
  SkillMgr.OnEnterGame()
  AutoPopUIManager.OnEnterGame()
  CrystalNucleusManager:OnEnterGame()
  FourPartyRivalryManager:OnEnterGame()
end

local function OutGameScene()
  this.playing = false
  ViewData.Clear()
  UIManager.HideAll()
  EventManager.Dispatch(Event.Scene_ShowLoading, "Back")
  CS.Framework.HUDTitleInfo.HUDTitleRender.Instance:OnLeaveGame()
  SceneController.OnLeaveGame()
  Scene.ResetTile()
  RoleManager.OnLeaveGame()
  DropItemManager.OnLeaveGame()
  BlockBuildManager.OnLeaveGame()
  ActivityManager.OnLeaveGame()
  RedNameManager.OnLeaveGame()
  TrapManager.OnLeaveGame()
  TransManager.OnLeaveGame()
  GraveManager.OnLeaveGame()
  TouchEvent.OnLeaveGame()
  PickupManager.OnLeaveGame()
  MapEffectManager.OnLeaveGame()
  DynamicTerrainController.OnLeaveGame()
  SceneGrassEffectManager.OnLeaveGame()
  GuideManager.OnLeaveGame()
  VipManager.OnLeaveGame()
  SceneWeatherEffect.DestroyEffect()
  SceneClientUpdateView.OnLeaveGame()
  SkillMgr.OnLeaveGame()
  AutoPopUIManager.OnLeaveGame()
  ActionManager.OnLeaveGame()
end

function GamePlay.OnLeaveGame()
  OutGameScene()
  Scene.OnLeaveGame()
end

function GamePlay.OnBack2Choose()
  OutGameScene()
  NetManager.Send(UserMessage.ReqGetRoleList)
end

function GamePlay.Update()
  if not this.playing or not Scene.loaded then
    return
  end
  Profiler.BeginSample("RoleManager.Update")
  RoleManager.Update()
  Profiler.EndSample()
  Profiler.BeginSample("DropItemManager.Update")
  DropItemManager.Update()
  Profiler.EndSample()
  Profiler.BeginSample("VipManager.Update")
  VipManager.Update()
  Profiler.EndSample()
  Profiler.BeginSample("TouchEvent.Update")
  TouchEvent.Update()
  Profiler.EndSample()
  Profiler.BeginSample("SkillMgr.Update")
  SkillMgr.Update()
  Profiler.EndSample()
  Profiler.BeginSample("BuffMgr.Update")
  BuffMgr.Update()
  Profiler.EndSample()
  Profiler.BeginSample("TrapManager.Update")
  TrapManager.Update()
  Profiler.EndSample()
  Profiler.BeginSample("SceneTouchEffect.Update")
  SceneTouchEffect.Update()
  Profiler.EndSample()
  Profiler.BeginSample("ActivityManager.Update")
  ActivityManager.Update()
  Profiler.EndSample()
  Profiler.BeginSample("RedNameManager.Update")
  RedNameManager.Update()
  Profiler.EndSample()
  Profiler.BeginSample("TaskManager.Update")
  TaskManager.Update()
  Profiler.EndSample()
  Profiler.BeginSample("MapMonsterLockManager.Update")
  MapMonsterLockManager.Update()
  Profiler.EndSample()
  Profiler.BeginSample("AutoTaskManage.Update")
  AutoTaskManage.Update()
  Profiler.EndSample()
  Profiler.BeginSample("PathFinderManager.Update")
  PathFinderManager.Update()
  Profiler.EndSample()
  Profiler.BeginSample("SceneWeatherEffect.Update")
  SceneWeatherEffect.Update()
  Profiler.EndSample()
  Profiler.BeginSample("SceneClientUpdateView.Update")
  SceneClientUpdateView.Update()
  Profiler.EndSample()
  Profiler.BeginSample("GameSettingsController.Update")
  GameSettingsController.Update()
  Profiler.EndSample()
end

function GamePlay.LateUpdate()
  if not this.playing then
    return
  end
  Profiler.BeginSample("Scene.Update")
  Scene.LateUpdate()
  Profiler.EndSample()
  Profiler.BeginSample("RoleManager.Update")
  RoleManager.LateUpdate()
  Profiler.EndSample()
  Profiler.BeginSample("DropItemManager.Update")
  DropItemManager.LateUpdate()
  Profiler.EndSample()
  Profiler.BeginSample("MainCamera.LateUpdate")
  MainCamera.LateUpdate()
  Profiler.EndSample()
end

GamePlay.Init()
