CommercializeLogManager = {}
local this = CommercializeLogManager
BusinessPayType = {
  None = enum(0),
  Main_First = enum(),
  Shop_Diamond = enum(),
  Welfare_Recharge = enum(),
  Welfare_EveryDayRecharge = enum(),
  Welfare_Gift = enum(),
  Vvip = enum(),
  Recycle_Gold = enum(),
  Drug_Gold = enum(),
  Depot_Gold = enum(),
  Shop_Silver = enum(),
  Opening_Gift = enum(),
  Silver_OverTime = enum(),
  Holiday_Prize = enum(),
  Holiday_Fireworks = enum(),
  LimitBuy = enum()
}
