local LuaClassManager = {}
LuaClass = {}

function LuaClassManager:Initialize()
  self.luaObject = require("LuaCore/LuaClass/Base/LuaObject")
  self:LoadAllClassFiles()
  self:BindAllMetaTables()
end

function LuaClassManager:BindAllMetaTables()
  for i, v in pairs(LuaClass) do
    self:BindMetatable(v, i)
  end
  LuaClass.__index = LuaClass
end

function LuaClassManager:BindMetatable(tbl, classname)
  if tbl and type(tbl) == "table" then
    local metatable = getmetatable(tbl)
    if (metatable == nil or tbl == metatable) and tbl ~= self.luaObject then
      setmetatable(tbl, self.luaObject)
    end
    tbl.__index = tbl
    tbl.__className = classname
  end
end

function LuaClassManager:LoadAllClassFiles()
  LuaClass.RedPointData = require("GamePlay/RedPoint/Base/RedPointData")
  LuaClass.AvatarManager = require("GamePlay/Mu2_Avatar/AvatarManager")
  LuaClass.Avatar = require("GamePlay/Mu2_Avatar/Avatar/Avatar")
  LuaClass.Player = require("GamePlay/Mu2_Avatar/AvatarBase/Player")
  LuaClass.Monster = require("GamePlay/Mu2_Avatar/AvatarBase/Monster")
  LuaClass.Npc = require("GamePlay/Mu2_Avatar/AvatarBase/Npc")
  LuaClass.Pet = require("GamePlay/Mu2_Avatar/AvatarBase/Pet")
  LuaClass.MainPlayer = require("GamePlay/Mu2_Avatar/AvatarMain/MainPlayer")
  LuaClass.OtherPlayer = require("GamePlay/Mu2_Avatar/AvatarMain/OtherPlayer")
  LuaClass.AvatarData = require("GameModel/Mu2_AvatarData/Avatar/AvatarData")
  LuaClass.PlayerData = require("GameModel/Mu2_AvatarData/AvatarBase/PlayerData")
  LuaClass.MonsterData = require("GameModel/Mu2_AvatarData/AvatarBase/MonsterData")
  LuaClass.NpcData = require("GameModel/Mu2_AvatarData/AvatarBase/NpcData")
  LuaClass.PetData = require("GameModel/Mu2_AvatarData/AvatarBase/PetData")
  LuaClass.MainPlayerData = require("GameModel/Mu2_AvatarData/AvatarMain/MainPlayerData")
  LuaClass.OtherPlayerData = require("GameModel/Mu2_AvatarData/AvatarMain/OtherPlayerData")
  LuaClass.PlayerData_GuardData = require("GameModel/Mu2_Guard/GuardData")
  LuaClass.LuaMemberDataManager = require("GameModel/Mu2_Member/LuaMemberDataManager")
  LuaClass.UpgradeMemberTipData = require("GameModel/UpgradeMemberTipData")
  LuaClass.PlayerData_EquipDataManager = require("GameModel/Mu2_Equip/EquipDataManager")
  LuaClass.PlayerData_JewelryData = require("GameModel/Mu2_Equip/Jewelry/JewelryData")
  LuaClass.PlayerData_EquipDataItem = require("GameModel/Mu2_Equip/EquipDataItem")
  LuaClass.CrossServerData = require("GameModel/Mu2_CrossServer/CrossServerData")
  LuaClass.SuitManager = require("GameModel/Mu2_Equip/Suit/SuitManager")
  LuaClass.SuitEquipItem_Base = require("GameModel/Mu2_Equip/Suit/Base/SuitEquipItem_Base")
  LuaClass.SuitEquipList_Base = require("GameModel/Mu2_Equip/Suit/Base/SuitEquipList_Base")
  LuaClass.SuitEquipItem_Normal = require("GameModel/Mu2_Equip/Suit/Normal/SuitEquipItem_Normal")
  LuaClass.SuitEquipList_Normal = require("GameModel/Mu2_Equip/Suit/Normal/SuitEquipList_Normal")
  LuaClass.SuitEquipItem_Archangel = require("GameModel/Mu2_Equip/Suit/Archangel/SuitEquipItem_Archangel")
  LuaClass.SuitEquipList_Archangel = require("GameModel/Mu2_Equip/Suit/Archangel/SuitEquipList_Archangel")
  LuaClass.SuitEquipItem_HolySpirit = require("GameModel/Mu2_Equip/Suit/HolySpirit/SuitEquipItem_HolySpirit")
  LuaClass.SuitEquipList_HolySpirit = require("GameModel/Mu2_Equip/Suit/HolySpirit/SuitEquipList_HolySpirit")
  LuaClass.SuitEquipItem_Archangel_Bless = require("GameModel/Mu2_Equip/Suit/Archangel_Bless/SuitEquipItem_Archangel_Bless")
  LuaClass.SuitEquipList_Archangel_Bless = require("GameModel/Mu2_Equip/Suit/Archangel_Bless/SuitEquipList_Archangel_Bless")
  LuaClass.SuitEquipItem_Archangel_Christmas = require("GameModel/Mu2_Equip/Suit/Archangel_Christmas/SuitEquipItem_Archangel_Christmas")
  LuaClass.SuitEquipList_Archangel_Christmas = require("GameModel/Mu2_Equip/Suit/Archangel_Christmas/SuitEquipList_Archangel_Christmas")
  LuaClass.SuitEquipItem_BingJian_SpringFestival = require("GameModel/Mu2_Equip/Suit/BingJian_SpringFestival/SuitEquipItem_BingJian_SpringFestival")
  LuaClass.SuitEquipList_BingJian_SpringFestival = require("GameModel/Mu2_Equip/Suit/BingJian_SpringFestival/SuitEquipList_BingJian_SpringFestival")
  LuaClass.SuitEquipItem_BingJian_DianYi = require("GameModel/Mu2_Equip/Suit/BingJian_DianYi/SuitEquipItem_BingJian_DianYi")
  LuaClass.SuitEquipList_BingJian_DianYi = require("GameModel/Mu2_Equip/Suit/BingJian_DianYi/SuitEquipList_BingJian_DianYi")
  LuaClass.SuitEquipItem_BingJian_BeachParty = require("GameModel/Mu2_Equip/Suit/BingJian_BeachParty/SuitEquipItem_BingJian_BeachParty")
  LuaClass.SuitEquipList_BingJian_BeachParty = require("GameModel/Mu2_Equip/Suit/BingJian_BeachParty/SuitEquipList_BingJian_BeachParty")
  LuaClass.SuitEquipItem_BingJian_YuanTianYueBai = require("GameModel/Mu2_Equip/Suit/BingJian_YuanTianYueBai/SuitEquipItem_BingJian_YuanTianYueBai")
  LuaClass.SuitEquipList_BingJian_YuanTianYueBai = require("GameModel/Mu2_Equip/Suit/BingJian_YuanTianYueBai/SuitEquipList_BingJian_YuanTianYueBai")
  LuaClass.SuitEquipList_BingJian = require("GameModel/Mu2_Equip/Suit/BingJian/SuitEquipList_BingJian")
  LuaClass.SuitEquipItem_BingJian = require("GameModel/Mu2_Equip/Suit/BingJian/SuitEquipItem_BingJian")
  LuaClass.BingJianData = require("GameModel/Mu2_Equip/Suit/BingJian/BingJianData")
  LuaClass.SuitEquipItem_HongZhuang = require("GameModel/Mu2_Equip/Suit/HongZhuang/SuitEquipItem_HongZhuang")
  LuaClass.SuitEquipList_HongZhuang = require("GameModel/Mu2_Equip/Suit/HongZhuang/SuitEquipList_HongZhuang")
  LuaClass.SuitEquipItem_Gem = require("GameModel/Mu2_Equip/Suit/Gem/SuitEquipItem_Gem")
  LuaClass.SuitEquipList_Gem = require("GameModel/Mu2_Equip/Suit/Gem/SuitEquipList_Gem")
  LuaClass.EquipIndexExtraItemManager = require("GameModel/Mu2_Equip/EquipIndexExtraItem/EquipIndexExtraItemManager")
  LuaClass.EquipIndexData = require("GameModel/Mu2_Equip/EquipIndexExtraItem/EquipIndexData")
  LuaClass.GemListData = require("GameModel/Mu2_Equip/EquipIndexExtraItem/Gem/GemListData")
  LuaClass.GemData = require("GameModel/Mu2_Equip/EquipIndexExtraItem/Gem/GemData")
  LuaClass.InlayDataManager = require("GameModel/Mu2_Inlay/InlayDataManager")
  LuaClass.InlayRedPointDataManager = require("GameModel/Mu2_Inlay/InlayRedPointDataManager")
  LuaClass.GlobalActivityDataManager = require("GameModel/Mu2_Activity/GlobalActivityDataManager")
  LuaClass.ActivityDataManager = require("GameModel/Mu2_Activity/ActivityDataManager")
  LuaClass.ActivityManagerBase = require("GameModel/Mu2_Activity/Base/ActivityManagerBase")
  LuaClass.ActivityDataBase = require("GameModel/Mu2_Activity/Base/ActivityDataBase")
  LuaClass.PlayActivityManager = require("GameModel/Mu2_Activity/PlayActivity/PlayActivityManager")
  LuaClass.PlayActivity = require("GameModel/Mu2_Activity/PlayActivity/PlayActivity")
  LuaClass.CoalitionSiege = require("GameModel/Mu2_Activity/PlayActivity/CoalitionSiege/CoalitionSiege")
  LuaClass.LuaKunShouBattleDataMgr = require("GameModel/Mu2_Activity/PlayActivity/KunShouBattle/LuaKunShouBattleDataMgr")
  require("GameModel/Mu2_Activity/PlayActivity/ThreeVsThree/Common/ThreeVsThreeUtility")
  LuaClass.ThreeVsThreeDataMgr = require("GameModel/Mu2_Activity/PlayActivity/ThreeVsThree/ThreeVsThreeDataMgr")
  LuaClass.CampInfo = require("GameModel/Mu2_Activity/PlayActivity/ThreeVsThree/CampInfo")
  LuaClass.CampPlayerInfo = require("GameModel/Mu2_Activity/PlayActivity/ThreeVsThree/CampPlayerInfo")
  LuaClass.SurrenderData = require("GameModel/Mu2_Activity/PlayActivity/ThreeVsThree/Surrender/SurrenderData")
  LuaClass.DuoQiCrossDataManager = require("GameModel/Mu2_Activity/PlayActivity/DuoQiCross/DuoQiCrossDataManager")
  LuaClass.DuoQiZhengBaDataManager = require("GameModel/Mu2_Activity/PlayActivity/DuoQiCross/DuoQiZhengBaDataManager")
  LuaClass.CommerceActivityManager = require("GameModel/Mu2_Activity/CommerceActivity/CommerceActivityManager")
  LuaClass.CommerceActivity = require("GameModel/Mu2_Activity/CommerceActivity/CommerceActivity")
  LuaClass.MiracleBattlePass = require("GameModel/Mu2_Activity/CommerceActivity/MiracleBattlePass/MiracleBattlePass")
  LuaClass.Co_serving_LianChongFanLiData = require("GameModel/Mu2_Activity/CommerceActivity/Combining_Service_Activity/Co_serving_LianChongFanLiData")
  LuaClass.CommercialRankingData = require("GameModel/Mu2_Activity/CommerceActivity/CommercialRankingData/CommercialRankingData")
  LuaClass.HolidayLuckyTurntableManager = require("GameModel/Mu2_Activity/HolidayLuckyTurntable/HolidayLuckyTurntableManager")
  LuaClass.CombineFirstGiftData = require("GameModel/Mu2_Activity/CommerceActivity/CombineFirstGiftData/CombineFirstGiftData")
  LuaClass.GoodFiftsEveryDayData = require("GameModel/Mu2_Activity/CommerceActivity/GoodFiftsEveryDayData/GoodFiftsEveryDayData")
  LuaClass.CombineTaskData = require("GameModel/Mu2_Activity/CommerceActivity/CombineTask/CombineTaskData")
  LuaClass.HolidayActivityManager = require("GameModel/Mu2_Activity/HolidayActivity/HolidayActivityManager")
  LuaClass.HolidayActivity = require("GameModel/Mu2_Activity/HolidayActivity/HolidayActivity")
  LuaClass.WorldCupGuessData = require("GameModel/Mu2_Activity/HolidayActivity/WorldCupGuess/WorldCupGuessData")
  LuaClass.SevenDayGiftData = require("GameModel/Mu2_Activity/HolidayActivity/SevenDayGift/SevenDayGiftData")
  LuaClass.FirecrackerTreasureHuntingDataMgr = require("GameModel/Mu2_Activity/HolidayActivity/FirecrackerTreasureHunting/FirecrackerTreasureHuntingDataMgr")
  LuaClass.YutulaixiData = require("GameModel/Mu2_Activity/HolidayActivity/Yutulaixi/YutulaixiData")
  LuaClass.ConnectionGift = require("GameModel/Mu2_Activity/HolidayActivity/ConnectionGift/ConnectionGiftManager")
  LuaClass.LuckyRebateData = require("GameModel/Mu2_Activity/HolidayActivity/LuckyRebate/LuckyRebateData")
  LuaClass.ShoppingSpreeData = require("GameModel/Mu2_Activity/HolidayActivity/ShoppingSpree/ShoppingSpreeData")
  LuaClass.Commercial_NetNiudanManager = require("GameModel/Mu2_Activity/HolidayActivity/Commercial_Niudan/Commercial_NetNiudanManager")
  LuaClass.RechargeActivityManager = require("GameModel/Mu2_Activity/RechargeActivity/RechargeActivityManager")
  LuaClass.RechargeActivity = require("GameModel/Mu2_Activity/RechargeActivity/RechargeActivity")
  LuaClass.OnHook_PointData = require("GameModel/Mu2_OnHook_Point/BossOnHook/OnHook_PointData")
  LuaClass.InComeOnHookPointManager = require("GameModel/Mu2_OnHook_Point/InComeOnHookPointManager")
  LuaClass.MapManager = require("GameModel/Mu2_Map/MapManager")
  LuaClass.MapData = require("GameModel/Mu2_Map/MapData")
  LuaClass.MapTransferData = require("GameModel/Mu2_Map/MapTransfer/MapTransferData")
  LuaClass.MapTransferListData = require("GameModel/Mu2_Map/MapTransfer/MapTransferListData")
  LuaClass.MinMapDataMgr = require("GameModel/Mu2_Map/MinMapDataMgr")
  LuaClass.MapMonsterPointList = require("GameModel/Mu2_Map/MapMonsterPoint/MapMonsterPointList")
  LuaClass.MapMonsterPoint = require("GameModel/Mu2_Map/MapMonsterPoint/MapMonsterPoint")
  LuaClass.ServerMonsterPointList = require("GameModel/Mu2_Map/ServerMonsterPoint/ServerMonsterPointList")
  LuaClass.ServerMonsterPoint = require("GameModel/Mu2_Map/ServerMonsterPoint/ServerMonsterPoint")
  LuaClass.UnionArmbandDataManager = require("GameModel/Mu2_UnionArmband/UnionArmbandDataManager")
  LuaClass.SceneManager = require("GamePlay/Mu2_Scene/SceneManager")
  LuaClass.SceneDataManager = require("GameModel/Mu2_Scene/SceneDataManager")
  LuaClass.SceneEffectDataManager = require("GameModel/Mu2_Scene/SceneEffect/SceneEffectDataManager")
  LuaClass.SceneEffectData = require("GameModel/Mu2_Scene/SceneEffect/SceneEffectData")
  LuaClass.SceneOnHookPointDataManager = require("GameModel/Mu2_Scene/ScenePoint/SceneOnHookPointDataManager")
  LuaClass.ScenePointDataManager = require("GameModel/Mu2_Scene/ScenePoint/SceneOnPlayerPointDataManager")
  LuaClass.SceneEffectProcessor = require("GamePlay/Mu2_Scene/SceneEffect/SceneEffectProcessor")
  LuaClass.SceneEffectObj = require("GamePlay/Mu2_Scene/SceneEffect/SceneEffectObj")
  LuaClass.GMDataManager = require("GameModel/GM_Tool/GM_DataManager")
  LuaClass.GMMessageTreeLogic = require("GameModel/GM_Tool/GM_MessageTreeLogic")
  LuaClass.GMSocket = require("socket")
  LuaClass.AttributeBaseData = require("GameModel/Mu2_Attribute/AttributeBaseData")
  LuaClass.PlayerAttributeData = require("GameModel/Mu2_Attribute/PlayerAttributeData")
  LuaClass.LuaExperienceBonusDataManager = require("GameModel/Mu2_ExperienceBonus/LuaExperienceBonusDataManager")
  LuaClass.PromptDataManager = require("GameModel/Mu2_Prompt/PromptDataManager")
  LuaClass.DeadStrengthenPromptDataManager = require("GameModel/Mu2_Prompt/DeadStrengthenPromptData/DeadStrengthenPromptDataManager")
  LuaClass.DeadStrengthenPromptData = require("GameModel/Mu2_Prompt/DeadStrengthenPromptData/DeadStrengthenPromptData")
  LuaClass.HolySealDataManager = require("GameModel/Mu2_HolySeal/HolySealDataManager")
  LuaClass.GameBookMgr = require("GameModel/GameBook/GameBookMgr")
  LuaClass.RedEquipLevelDataManager = require("GameModel/Mu2_Equip/RedEquip/RedEquipLevelDataManager")
  LuaClass.MasterSysData = require("GameModel/Mu2_MasterSys/MasterSysData")
  LuaClass.XiLianManager = require("GameModel/Mu2_XiLian/XiLianManager")
  LuaClass.RegenerateManager = require("GameModel/Mu2_Regenerate/RegenerateManager")
  LuaClass.HolySpiritManager = require("GameModel/Mu2_HolySpirit/HolySpiritManager")
  LuaClass.ShieldDataManager = require("GameModel/Mu2_Shield/ShieldDataManager")
  LuaClass.BagGridCalcManager = require("GameModel/Mu2_BagGridCalculate/BagGridCalcManager")
  LuaClass.BagGrid = require("GameModel/Mu2_BagGridCalculate/BagGrid")
  LuaClass.CameraObj = require("GamePlay/Mu2_Camera/CameraObj")
  LuaClass.CameraManager = require("GamePlay/Mu2_Camera/CameraManager")
  LuaClass.MasterSkillDataMgr = require("GameModel/Mu2_MasterSkill/MasterSkillDataMgr")
  LuaClass.KLTRuinsManager = require("GameModel/Mu2_KLTRuins/KLTRuinsManager")
  LuaClass.VirusCircleManager = require("GameModel/Mu2_KLTRuins/VirusCircle/VirusCircleManager")
  LuaClass.VirusCircle_Scene = require("GameModel/Mu2_KLTRuins/VirusCircle/VirusCircle_Scene")
  LuaClass.VirusCircle_MiniMap = require("GameModel/Mu2_KLTRuins/VirusCircle/VirusCircle_MiniMap")
  LuaClass.KLTSettleManager = require("GameModel/Mu2_KLTRuins/KLTSettle/KLTSettleManager")
  LuaClass.SkillManager = require("GameModel/Mu2_Skill/SkillManager")
  LuaClass.SkillGroupAdditionManager = require("GameModel/Mu2_Skill/SkillGroupAdditionManager")
  LuaClass.Active_TurntableUIDataMgr = require("GameModel/Mu2_Activity/Active_TurntableUI/Active_TurntableUIDataMgr")
  LuaClass.CoalitionManager = require("GameModel/Mu2_Coalition/CoalitionManager")
  LuaClass.CoalitionInfo = require("GameModel/Mu2_Coalition/CoalitionInfo")
  LuaClass.Union = require("GameModel/Mu2_Union/UnionInfo")
  LuaClass.TransferStoneManager = require("GameModel/Mu2_TransferStone/TransferStoneManager")
  LuaClass.RuneManager = require("GameModel/Mu2_Rune/RuneManager")
  LuaClass.RunesFusionDataMgr = require("GameModel/Mu2_Rune/RunesFusionDataMgr")
  LuaClass.HolyRingManager = require("GameModel/Mu2_HolyRing/HolyRingManager")
  LuaClass.HolyRingHoleData = require("GameModel/Mu2_HolyRing/HolyRingHoleData")
  LuaClass.HolyRingHoleItemData = require("GameModel/Mu2_HolyRing/HolyRingHoleItemData")
  LuaClass.HolyRingBagItemData = require("GameModel/Mu2_HolyRing/HolyRingBagItemData")
  LuaClass.SacredBoneManager = require("GameModel/Mu2_SacredBone/SacredBoneManager")
  LuaClass.SacredBoneBagData = require("GameModel/Mu2_SacredBone/SacredBoneBagData")
  LuaClass.SacredBoneData = require("GameModel/Mu2_SacredBone/SacredBoneData")
  LuaClass.SacredBoneEquipData = require("GameModel/Mu2_SacredBone/SacredBoneEquipData")
  LuaClass.RoleCircleEffectManager = require("GameModel/Mu2_RoleCircleEffect/Base/RoleCircleEffectManager")
  LuaClass.RoleCircleEffectLoader = require("GameModel/Mu2_RoleCircleEffect/Base/RoleCircleEffectLoader")
  LuaClass.RoleCircleEffectShowRule = require("GameModel/Mu2_RoleCircleEffect/Base/RoleCircleEffectShowRule")
  LuaClass.RoleCircleEffectProcessorBase = require("GameModel/Mu2_RoleCircleEffect/Base/RoleCircleEffectProcessorBase")
  LuaClass.RoleReinCircleEffectProcessor = require("GameModel/Mu2_RoleCircleEffect/RoleReinCircleEffectProcessor")
  LuaClass.RoleHolyCircleEffectProcessor = require("GameModel/Mu2_RoleCircleEffect/RoleHolyCircleEffectProcessor")
  LuaClass.ViewRoleHolyCircleEffectProcessor = require("GameModel/Mu2_RoleCircleEffect/ViewRoleHolyCircleEffectProcessor")
  LuaClass.Appear_CoutureData = require("GameModel/Mu2_Appear/Appear_CoutureData")
  LuaClass.WarAllianceRedEnvelopeData = require("GameModel/WarAllianceRedEnvelope/WarAllianceRedEnvelopeData")
  LuaClass.SpringActivityManger = require("GameModel/SpringActivityMgr/SpringActivityManger")
  LuaClass.PrivilegeManager = require("GameModel/Mu2_Privilege/PrivilegeManager")
  LuaClass.PrivilegeObject = require("GameModel/Mu2_Privilege/PrivilegeObject")
  LuaClass.HolySkeletonIntensifyManager = require("GameModel/Mu2_HolySkeleton/HolySkeletonIntensifyManager")
  LuaClass.HolySkeletonIntensifyPlaceData = require("GameModel/Mu2_HolySkeleton/HolySkeletonIntensifyPlaceData")
  LuaClass.HolySkeletonIntensifyHoleData = require("GameModel/Mu2_HolySkeleton/HolySkeletonIntensifyHoleData")
  LuaClass.EffectManager = require("GameModel/Mu2_Effect/EffectManager")
  LuaClass.EffectProcessor = require("GameModel/Mu2_Effect/Base/EffectProcessor")
  LuaClass.EffectObject = require("GameModel/Mu2_Effect/Base/EffectObject")
  LuaClass.EffectActionUtility = require("GameModel/Mu2_Effect/EffectActionUtility")
  LuaClass.EffectObject_Buff = require("GameModel/Mu2_Effect/BuffEffect/EffectObject_Buff")
  LuaClass.EffectProcessor_Buff = require("GameModel/Mu2_Effect/BuffEffect/EffectProcessor_Buff")
  LuaClass.EffectObject_UI = require("GameModel/Mu2_Effect/UIEffect/EffectObject_UI")
  LuaClass.EffectObject_Title = require("GameModel/Mu2_Effect/TitleEffect/EffectObject_Title")
  LuaClass.EffectObject_UITitle = require("GameModel/Mu2_Effect/TitleEffect/EffectObject_UITitle")
  LuaClass.TimeLimitedActivityManager = require("GameModel/Mu2_Activity/TimeLimitedActivity/TimeLimitedActivityManager")
  LuaClass.TimeLimitedActivity = require("GameModel/Mu2_Activity/TimeLimitedActivity/TimeLimitedActivity")
  LuaClass.OpenServerInvestmentData = require("GameModel/Mu2_Activity/TimeLimitedActivity/OpenServerInvestment/OpenServerInvestmentData")
  LuaClass.TimeLimited_MiracleBattlePass = require("GameModel/Mu2_Activity/TimeLimitedActivity/MiracleBattlePass/TimeLimited_MiracleBattlePass")
  LuaClass.RechargeSurpriseData = require("GameModel/Recharge_Surprise/RechargeSurpriseData")
  LuaClass.HolidayInvestData = require("GameModel/Mu2_Activity/HolidayActivity/HolidayInvest/HolidayInvestData")
  LuaClass.RewriteNamingData = require("GameModel/Mu2_RewriteNaming/RewriteNamingData")
  LuaClass.FunctionDisableManager = require("GameModel/Mu2_FunctionDisable/FunctionDisableManager")
  LuaClass.Instance_ClimbTowerManager = require("GameModel/Mu2_Instance_ClimbTowerUI/Instance_ClimbTowerManager")
  LuaClass.Activity_SeaChestManager = require("GameModel/Mu2_Activity_SeaChest/Activity_SeaChestManager")
  LuaClass.NewRuneDataManager = require("GameModel/Mu2_NewRune/NewRuneDataManager")
  LuaClass.SpaceCrackActivityData = require("GameModel/SpaceCrack/SpaceCrackActivityData")
  LuaClass.EnchantEquipManager = require("GameModel/EquipEnchant/EnchantEquipManager")
  LuaClass.EnchantEquipIndexData = require("GameModel/EquipEnchant/EnchantEquipIndexData")
  LuaClass.EnchantEquipIndexUpgradeItemData = require("GameModel/EquipEnchant/EnchantEquipIndexUpgradeItemData")
  LuaClass.EnchantEquipBagItemData = require("GameModel/EquipEnchant/EnchantEquipBagItemData")
  LuaClass.EnchantmentSmeltingManager = require("GameModel/EquipEnchant/EnchantmentSmeltingManager")
  LuaClass.Task_EarlyGoldData = require("GameModel/Mu2_Task_EarlyGoldDataConfig/Task_EarlyGoldData")
  LuaClass.OtherWelfareData = require("GameModel/Mu2_OtherBenefits/OtherWelfareData")
  LuaClass.JoinVipData = require("GameModel/Mu2_JoinVip/JoinVipData")
  LuaClass.SiFangZhengBaData = require("GameModel/SiFangZhengBa/SiFangZhengBaData")
  LuaClass.Team3V3Data = require("GameModel/Team3V3/Team3V3Data")
end

function LuaClassManager.OnTableDestroyed(tbl)
  if tbl == nil then
    return
  end
  if tbl.OnDestruct then
    tbl:OnDestruct()
  end
end

return LuaClassManager
