require("Utility/Direction8Utility")
require("Utility/MathUtility")
require("Utility/RoleEquipUtility")
require("Utility/MaterialUtility")
require("Utility/ParseUtility")
require("Utility/RoleUtility")
require("Utility/ItemUtility")
require("Utility/LocalizationUtility")
require("Utility/TimeUtility")
require("Utility/PrintDumpUtility")
require("Utility/MUString")
require("Utility/ColorUtility")
require("Utility/DropItemUtility")
require("Utility/MountUtility")
require("Utility/LimitUtility")
require("Utility/ChatUtility")
require("Utility/BlockerUtility")
require("Utility/VoiceUtility")
require("Utility/CSharpBindFuncUtility")
require("Utility/TipUtility")
require("Utility/BuffUtility")
require("Utility/FloatingWordUtility")
require("Utility/FloatingExpUtility")
require("Utility/FloatingTipUtility")
require("Utility/GuideUtility")
require("Utility/UIEffectUtility")
require("Utility/TextPromptUtility")
require("Utility/AnimatorUtility")
require("Utility/SpaceCalcUtility")
require("Utility/SceneUtility")
require("Utility/UIMonsterUtility")
require("Utility/AudioUtility")
require("Utility/MuCallBackUtility")
require("Utility/AdapterUtility")
require("Utility/NavigationUtility")
require("Utility/ProfessionalUtility")
require("Utility/PropsTransUtility")
require("Utility/WarAllianceUtility")
require("Utility/ShowBtnItemUtility")
require("Utility/GemUtility")
require("Utility/AttributeUtility")
require("Utility/TeamUtility")
DelayRefreshManager = require("Utility/DelayRefreshManager")
UIUtility = require("Utility/UIUtility/UIUtility")
Utility = {}

function Utility.Update()
  FloatingWordUtility.Update()
end
